domain: olib6542.github.io
url: https://olib6542.github.io
markdown: kramdown
repository: olib6542/olib6542.github.io
title: Blog
# email: # TODO setup an inbox for this
description: Hopefully my future blog site
theme: minima
exclude:
  - _ideas
  - Gemfile

plugins:
  - jekyll-feed # RSS feed

site:
  paginate: true
